In [79]:
print('hello')

hello

In [80]:
import pandas as pd

In [81]:
person = {
    'name': ['pardeep','arson','ace'],
    'age': [22,22,12]
}
person_df = pd.DataFrame(person)

In [82]:
df = pd.read_excel('movies_data.xlsx')
df.head()

/home/arson/.cache/pypoetry/virtualenvs/arson-guvi-NQVoKMHS-py3.12/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,436,22,9.0,481,691,1,10718,88,69.0,8.0
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,2,0.0,4,0,1,5,1,1.0,4.8
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,81,12,6.0,108,226,0,4849,45,48.0,8.3
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,136,23,18.0,203,12000,1,111841,413,260.0,8.3
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,426,20,3.0,455,926,1,7431,84,71.0,8.0

In [83]:
df.Title

0       Intolerance: Love's Struggle Throughout the Ages
1                         Over the Hill to the Poorhouse
2                                         The Big Parade
3                                             Metropolis
4                                          Pandora's Box
                              ...
1333                                    Twin Falls Idaho
1334                       Universal Soldier: The Return
1335                                       Varsity Blues
1336                                      Wild Wild West
1337                                      Wing Commander
Name: Title, Length: 1338, dtype: str

In [84]:
df_subset= df[['Title','Year','Genres']]
df_subset

,Title,Year,Genres
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War
1,Over the Hill to the Poorhouse,1920,Crime|Drama
2,The Big Parade,1925,Drama|Romance|War
3,Metropolis,1927,Drama|Sci-Fi
4,Pandora's Box,1929,Crime|Drama|Romance
...,...,...,...
1333,Twin Falls Idaho,1999,Drama
1334,Universal Soldier: The Return,1999,Action|Sci-Fi
1335,Varsity Blues,1999,Comedy|Drama|Romance|Sport
1336,Wild Wild West,1999,Action|Comedy|Sci-Fi|Western
1337,Wing Commander,1999,Action|Adventure|Sci-Fi

### Loc Function

In [85]:
df.loc[0]

Title                          Intolerance: Love's Struggle Throughout the Ages
Year                                                                        1916
Genres                                                         Drama|History|War
Language                                                                     NaN
Country                                                                      USA
Content Rating                                                         Not Rated
Duration                                                                     123
Aspect Ratio                                                                1.33
Budget                                                                  385907.0
Gross Earnings                                                               NaN
Director                                                           D.W. Griffith
Actor 1                                                             Lillian Gish
Actor 2                                                                Mae Marsh
Actor 3                                                              Walter Long
Facebook Likes - Director                                                    204
Facebook Likes - Actor 1                                                     436
Facebook Likes - Actor 2                                                      22
Facebook Likes - Actor 3                                                     9.0
Facebook Likes - cast Total                                                  481
Facebook likes - Movie                                                       691
Facenumber in posters                                                          1
User Votes                                                                 10718
Reviews by Users                                                              88
Reviews by Crtiics                                                          69.0
IMDB Score                                                                   8.0
Name: 0, dtype: object

In [86]:
## to access the last row, 
df.loc[df.shape[0]]

KeyError: 1338

In [ ]:
# 0th , 99th and last

df.loc[[0,99,df.shape[0]-1]]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,436,22,9.0,481,691,1,10718,88,69.0,8.0
99,A Hard Day's Night,1964,Comedy|Musical,English,UK,Approved,87,1.75,560000.0,515005.0,...,785,725,704.0,2538,0,1,31429,219,105.0,7.7
1337,Wing Commander,1999,Action|Adventure|Sci-Fi,English,USA,PG-13,100,2.35,30000000.0,11576087.0,...,811,586,362.0,2497,858,3,14747,338,85.0,4.1

### iloc function

In [ ]:
df_iloc = df.iloc[[0,99,-1]]
df_iloc

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,436,22,9.0,481,691,1,10718,88,69.0,8.0
99,A Hard Day's Night,1964,Comedy|Musical,English,UK,Approved,87,1.75,560000.0,515005.0,...,785,725,704.0,2538,0,1,31429,219,105.0,7.7
1337,Wing Commander,1999,Action|Adventure|Sci-Fi,English,USA,PG-13,100,2.35,30000000.0,11576087.0,...,811,586,362.0,2497,858,3,14747,338,85.0,4.1

In [ ]:
# to get the exact cell
df.iloc[3,1]

np.int64(1927)

In [ ]:
df.iloc[1:4,1]

1    1920
2    1925
3    1927
Name: Year, dtype: int64

In [ ]:
df.iloc[[2,4,6,8],[1,5]]

   Year Content Rating
2  1925      Not Rated
4  1929      Not Rated
6  1930         Passed
8  1933        Unrated

In [ ]:
group_df = df.groupby('Year')['IMDB Score'].mean()
group_df.tail()

Year
1995    6.565714
1996    6.418182
1997    6.485593
1998    6.485821
1999    6.407143
Name: IMDB Score, dtype: float64

In [ ]:
df_1 =df.groupby(['Country','Year'])[['IMDB Score','Duration']].mean()
df_1.tail(10)

                   IMDB Score    Duration
Country      Year
USA          1993    6.678947  122.789474
             1994    6.673333  112.644444
             1995    6.561667  113.950000
             1996    6.367442  110.662791
             1997    6.400000  111.765957
             1998    6.418000  110.420000
             1999    6.326515  107.924242
West Germany 1967    6.000000   80.000000
             1981    8.400000  293.000000
             1984    7.400000   94.000000

In [ ]:
# unique content rat9ng
df.groupby('Country')['Content Rating'].nunique()
df.groupby('Country')['Content Rating'].value_counts()

Country       Content Rating
Aruba         R                 1
Australia     R                 8
              PG-13             5
              PG                3
              G                 2
                               ..
USA           NC-17             3
              TV-G              1
West Germany  R                 1
              PG                1
              M                 1
Name: count, Length: 78, dtype: int64

In [ ]:
df['IMDB Score'].agg(['sum','mean','min'])

sum     8967.500000
mean       6.702167
min        2.300000
Name: IMDB Score, dtype: float64

In [ ]:
df.groupby('Country')['IMDB Score'].agg(['sum','mean','min']).head()

             sum      mean  min
Country
Aruba        4.8  4.800000  4.8
Australia  116.2  6.455556  4.9
Brazil      14.4  7.200000  6.4
Canada     158.4  6.336000  2.8
China        7.8  7.800000  7.8

### Creatign and manupulating the dataframe

In [ ]:
data = ['arson',22,'M']
index = ['name','age','Gender']

s= pd.Series(data, index=index)

In [ ]:
s.loc['name']

'arson'

In [ ]:
s.iloc[0]

'arson'

In [ ]:
person_df

      name  age
0  pardeep   40
1    arson   40
2      ace   40

In [89]:
person_df['age'][0] = 12

/tmp/ipykernel_1452353/992076656.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  person_df['age'][0] = 12

In [90]:
person_df

      name  age
0  pardeep   22
1    arson   22
2      ace   12

In [93]:
df_A = [{
    'name':'A',
    'age': 'B'
},index=[0,1]]

df_B = [{
    'name':'A',
    'age': 'B'
},index=[2,3]]

df_C= [{
    'name':'A',
    'age': 'B'
},index=[4,5]]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (4292690371.py, line 4)